;;; init-fonts.el --- Fonts Configuration  -*- lexical-binding: t; -*-

;; Copyright (C) 2020  T_Fighting

;; Author: T_Fighting <545298210@qq.com>
;; Keywords: Fonts


;; ;; Set unicode fonts
(set-fontset-font t 'unicode "Symbola" nil 'prepend)

;; Auto generated by cnfonts
;; <https://github.com/tumashu/cnfonts>

(set-face-attribute
 'default nil
 :font (font-spec :name "-outline-Lucida Console-normal-normal-normal-mono-*-*-*-*-c-*-iso10646-1"
                  :weight 'normal
                  :slant 'normal
                  :size 12.5))
(dolist (charset '(kana han symbol cjk-misc bopomofo))
  (set-fontset-font
   (frame-parameter nil 'font)
   charset
   (font-spec :name "-outline-KaiTi_GB2312-normal-normal-normal-mono-*-*-*-*-c-*-iso10646-1"
              :weight 'normal
              :slant 'normal
              :size 15.0)))

(provide 'init-fonts)

;;; init-fonts.el ends here.
